name: Metrics

on:
  schedule: [{cron: '0 0 * * *'}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gerar Estatísticas Gerais
        uses: lowlighter/metrics@latest
        with:
          filename: stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, repositories, metadata"
          config_timezone: America/Sao_Paulo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update projects
        run: python scripts/update_projects.py
        env:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          
      - name: Gerar Linguagens Mais Usadas
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

      - name: Gerar Calendário / Sequência
        uses: lowlighter/metrics@latest
        with:
          filename: streak.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Gerar Gráfico de Atividade
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: push, pr, issue
          plugin_activity_limit: 5

      - name: Commit generated metrics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics and projects"
          file_pattern: "*.svg README.md"
          
